proxy:
    listen: ":1545"
    server: "http://localhost:1544"
    max-req-body-size: 16000000
    check-url: true
    check-query: true
    check-filenames: true
    check-json: true
    check-all-fields: true
    check-fields: [] # use when check-all-fields is false
